### ISSUE TITLE
Offset to the background in the neighborhood

### ISSUE THREAD

**Issue by plumer** [zagortenay333/Harmattan#10]
I'm using Elementary OS Freya.
The background near the conky windows seems to be shifted vertically.

![screenshot from 2015-12-17 11 37 22](https://cloud.githubusercontent.com/assets/8614545/11860717/b1bf2300-a4b2-11e5-810d-5c863c958165.png)

**Comment by zagortenay333** [comment]
Elementary doesn't play well with conky's fake transparency unfortunately.

You could try to play around with the `own_window_type` variable a bit. Otherwise, you will have to use a program like feh to render the background.

**Comment by plumer** [comment]
I have tried all possible values of `own_window_type` given in the comments but there is simply no improvement.
Thanks anyway, and I would try your themes under other desktop environments.
