### ISSUE TITLE
Weather days does not refresh

### ISSUE THREAD

**Issue by qcol** [zagortenay333/Harmattan#11]
I installed conky/Harmattan in Wednesday... today is Friday but I still have 3-day weather WED / THU / FRI.  Shouldn't it be FRI / SAT / SUN?

**Comment by zagortenay333** [comment]
What happens when you restart conky? Any errors in the terminal?

**Comment by qcol** [comment]
I don't know why but from yesterday all  is OK... today I have SUN/MON/TUE so correct... I will let you know if it is repeated
