### ISSUE TITLE
New weather provider needed

### ISSUE THREAD

**Issue by zagortenay333** [zagortenay333/Harmattan#12]
Yahoo requires that a **powered by Yahoo** logo be added with their data: https://developer.yahoo.com/attribution/

There is no way I can do that in this conky, or any other ones I made, due to aesthetical reasons as well as space constraints, and I cannot add a reveal-on-hover link either, because of conky's limitations.

Also, I would need to be able to distribute the potential API key in the conf file; otherwise, the user would have to make an account on a weather page just to be able to use this conky.

**Comment by VentsiKonov** [comment]
I'd recommend this one (http://openweathermap.org) - I've not used it but it seems reasonable on the free plan. Also you could potentially just pretend to be a browser, get the content and parse it.

**Comment by zagortenay333** [comment]
Yeah, I'll use that one. I opened this issue against conky https://github.com/brndnmtthws/conky/issues/210

Still waiting for the dev to respond.

**Comment by plikhari** [comment]
You can use conkywx - like @VentsiKonov suggested - we just pretend to be a browser and parse the content. Have a look at it - use it modify it enjoy it. Many weather websites used.

**Comment by zagortenay333** [comment]
@plikhari I'm still waiting for that issue I opened against conky. The dev has yet not responded..

**Comment by zagortenay333** [comment]
Fixed.
