### ISSUE TITLE
Transparent border Ubuntu 14.04

### ISSUE THREAD

**Issue by Corsseir** [zagortenay333/Harmattan#13]
Hey!

What am I doing wrong?
![screenshot from 2016-03-01 22 27 43](https://cloud.githubusercontent.com/assets/11137173/13442534/07e56a84-dffd-11e5-9568-f6d50b3b4955.png)

**Comment by zagortenay333** [comment]
Compiz is rendering a shadow on all windows including conky. Either make an exception for it in ccsm or play around with the `own_window_type` variable.

The alignment is a known issue, and there is no solution for right now it other then manually fixing the `voffset` variable. Hopefully I might fix eventually.
