### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ArchYouSa2** [zagortenay333/Harmattan#15]
Hi!

I can't figure out what's wrong here.
Everything is so light, I can't even read it.
![harmattan](https://cloud.githubusercontent.com/assets/18367042/14404498/0efbfa2e-fe78-11e5-86c6-446725fd634f.png)

**Comment by zagortenay333** [comment]
Weird. Looking into and can't figure it out right now either..

**Comment by ArchYouSa2** [comment]
I don't know if this helps:
![kanki](https://cloud.githubusercontent.com/assets/18367042/14404650/3003561e-fe7c-11e5-9f39-5c633ac59844.png)

My config file without template6&7:
http://pastebin.com/PJJU9L1t

**Comment by zagortenay333** [comment]
OK, fixed with 0f59c2d93b627ab5b77e500eb8dc3eec8dee02b0

I didn't notice `xftalpha` was set to 0.

**Comment by ArchYouSa2** [comment]
Thank you so much
