### ISSUE TITLE
Always On Top

### ISSUE THREAD

**Issue by Superman800** [zagortenay333/Harmattan#16]
Hello,
Could you tell me what went wrong here?
It's always on top.
![over](https://cloud.githubusercontent.com/assets/18398362/14427929/27b85cf8-fff7-11e5-84ba-fd45fbb780ec.png)

Here is the code:
https://paste.kde.org/pzlpylxni
It runs on LXDE/Manjaro.

**Comment by zagortenay333** [comment]
Play around with the `own_window_type` config.

**Comment by Superman800** [comment]
Unfortunately none of them worked well.
normal and override did the same thing, conky was on the top.
panel and dock were simply weird, and didn't care about the x,y gaps
desktop was kinda okay, but when I clicked on the desktop, it disappeared.

So I played around with own_window_hints.

This is my conkyrc at the moment. It works as expected, I'm not sure whether it overwrites the upper hints or blends with it, but finally it works:

---

## --  Window Specifications

gap_x=750,
gap_y=22,
minimum_height=270,
minimum_width=268,
own_window=true,
own_window_type="normal",
own_window_transparent=true,
own_window_hints="undecorated,below,above,sticky,skip_taskbar,skip_pager",
own_window_hints="below,undecorated,skip_taskbar",
border_inner_margin=0,
border_outer_margin=0,
--alignment="middle_middle",
--own_window_argb_visual=true,
--own_window_argb_value=0,

**Comment by zagortenay333** [comment]
Wait a sec. I have `below` and then `above` listed there. That's probably the culprit. Could you check it? Just remove the above, and remove your config too. If that's the culprit I'll fix it.

**Comment by Superman800** [comment]
yep-yep, own_window_hints=above is the main culprit here, conky works well without it!
I removed it and my config too, everything is good (except the common voffset issue)

**Comment by zagortenay333** [comment]
Fixed with 92cfd0d.
