### ISSUE TITLE
View Problem

### ISSUE THREAD

**Issue by mohammadayn** [zagortenay333/Harmattan#22]
Hi
Why does it look like this and say "conky: Unable to load image '/home/mohammad/.cache/weather-1.png'"?
![screenshot from 2016-07-24 14-56-54](https://cloud.githubusercontent.com/assets/10381709/17083278/d87ebbcc-51af-11e6-91a4-24c9d7c07399.jpg)

**Comment by moraisaugusto** [comment]
up!

**Comment by zagortenay333** [comment]
Oh forgot bout this...

No clue. Are you on ubuntu and did you install `conky-all`?

**Comment by moraisaugusto** [comment]
Yes. I tried all suggestions here: http://askubuntu.com/questions/482490/harmattan-conky-on-14-04-with-variety-wallpaper-conky-border-stays-as-old-wallp

Seems a gtk problem .

**Comment by zagortenay333** [comment]
This shouldn't have anything to do with GTK. So what distro are you on?

**Comment by moraisaugusto** [comment]
debian - testing
Gnome 3.20

The problem with alignment I already fix. It's just to change the value of the first 'voffset' in .conkyrc of each theme. Now I'm trying to fix the blackboards.

**Comment by zagortenay333** [comment]
That's a known issue #3 .

**Comment by mohammadayn** [comment]
Hi
I use ubuntu-gnome 16.04, and installed conky-all.

**Comment by zagortenay333** [comment]
Did you fix this? What is the output in the terminal?

**Comment by soyuka** [comment]
Same issue here:

```

conky: desktop window (ee) is root window
conky: window type - normal
conky: drawing to created window (0x2400001)
conky: drawing to double buffer
conky: forked to background, pid is 8597
```

Output:

![conky](https://cloud.githubusercontent.com/assets/1321971/17961558/cb3654f0-6aac-11e6-87eb-f10f5139eed2.png)

Using i3. conky-all installed, font installed

**Comment by zagortenay333** [comment]
@soyuka you don't have the same problem. This issue is about him not having the image load. Gonna close this due to inactivity though.

**Comment by soyuka** [comment]
Though screenshots look exactly the same (pictures are loading to me but alignment has issues).

**Comment by zagortenay333** [comment]
@soyuka Like I said, it's a known issue and has been reported #1 . There is no fix for it. Conky isn't really meant to be used the way I do it in Harmattan. It has a very poor integration of images and text. The bug has also been reported against conky as well , and I think it won't ever be fixed.

**Comment by soyuka** [comment]
Oh alright thanks!

**Comment by arnaud-lecat** [comment]
For me it was just a bad call of the JQ library. Here is how i fixed it

Replace all .weather[n] and .list[n] (where n is an index) by .weather.[n] and .list.[n]

This is how jq works. Hope it will work 4U !

**Comment by tomtobac** [comment]
I did what @jarod51 said but it keeps show in console:
```
conky: Unable to load image '/home/tom/.cache/weather-1.png'
sh: 1: jq: not found
``

**Comment by cortexx** [comment]
@tomtobac 
If ```dpkg -l jq``` command return nothing, you'll need to install JQ software.
To do this : ```sudo apt install jq```
If JQ is already installed on your system, check if your PATH environment variable is OK and contain ```/usr/bin/```.

**Comment by tomtobac** [comment]
I did and worked, Thanks! :)
