### ISSUE TITLE
Missing network interface + Suggestion

### ISSUE THREAD

**Issue by PyGeek03** [zagortenay333/Harmattan#23]
I really appreciate your effort to have listed 10 possible network interfaces, yet that still doesn't cover the network interfaces on my laptop (which are enp0s25 and wlo1, by the way). Inspired by your work, I have written a command to get the working network interface based on output from /proc/net/route:
`cat /proc/net/route | tail -n +2 | head -n1 | awk '{print $1;}'`
However, this command can only display the working (connected) network interface, not all available network interfaces on a computer. After some googling, I've found out 2 commands that list all available network interfaces:
`ifconfig -a`
or
`ip link show`
I think that maybe you can add these commands into the README file so that other people will be able to quickly identify available network interfaces on their computer.

**Comment by zagortenay333** [comment]
I really wish I could simply find the network automatically, but I guess It can't be done universally for all distros...

I want to avoid adding distro-specific solutions for any issue, but I'll add a note that it could be a potential problem.

**Comment by zagortenay333** [comment]
Forgot about this one.. I added a simple notice on it in the README.md with 916e5892eb069a242372c7521df4c499c94b583e
