### ISSUE TITLE
'No such configuration' error

### ISSUE THREAD

**Issue by PabloValor** [zagortenay333/Harmattan#24]
I followed all the steps and I'm having this error when I execute the `conky` command from the terminal.
I uninstalled conky and back to install again but the error persists.
![selection_031](https://cloud.githubusercontent.com/assets/6534833/17643155/6580a08a-6137-11e6-97cb-e123dfdaa084.png)

**Comment by zagortenay333** [comment]
What version of conky did you install?

**Comment by PabloValor** [comment]
Thanks for the fast reply.
I'll paste it the result
`conky -V
Conky 1.9.0 compiled Wed Feb 19 18:40:50 UTC 2014 for Linux 3.2.0-54-generic (x86_64)

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 X11:
- Xdamage extension
- XDBE (double buffer extension)
- Xft
- ARGB visual
  
  Music detection:
- Audacious
- MPD
- MOC
- XMMS2
  
  General:
- math
- hddtemp
- portmon
- Curl
- RSS
- Weather (METAR)
- Weather (XOAP)
- wireless
- config-output
- Imlib2
- apcupsd
- iostats
- ncurses
- Lua
  
  Lua bindings:
  - Cairo
  - Imlib2
    `

**Comment by zagortenay333** [comment]
I guess you didn't you read  the README.md file?

The master branch is for conky `1.10`.
Older versions: https://github.com/zagortenay333/Harmattan/releases

**Comment by PabloValor** [comment]
Oh yes, that was the problem! Thank you!
Now it's working, but looks a little odd. I have already installed droid sans.
![selection_032](https://cloud.githubusercontent.com/assets/6534833/17644639/708fb116-6162-11e6-9e71-6f8c6a7d7589.png)

**Comment by zagortenay333** [comment]
That's another issue. It's already reported.
