### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ogerasymenko** [zagortenay333/Harmattan#25]
Hello. I'm doing like in installation section but not work. Ubuntu16.04. 
Here is output:
$ conky
conky: desktop window (200000a) is subwindow of root window (225)
conky: window type - normal
conky: drawing to created window (0x3600001)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: forked to background, pid is 17055
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat '/home/user/.harmattan-assets/icons/#fff__32/.png': No such file or directory
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat '/home/user/.harmattan-assets/photos/smallest/.png': No such file or directory
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat '/home/user/.harmattan-assets/icons/#fff__32/.png': No such file or directory
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7

**Comment by zagortenay333** [comment]
Are you on ubuntu? If so, try installing `conky-all`

**Comment by ogerasymenko** [comment]
Thank for your advice, it helps. Now output  next:
cp: cannot stat '/home/user/.harmattan-assets/icons/#fff__32/.png': No such file or directory
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat '/home/user/.harmattan-assets/icons/#fff__32/.png': No such file or directory
parse error: Invalid numeric literal at line 1, column 7

**Comment by zagortenay333** [comment]
What version of conky are you using?

**Comment by ogerasymenko** [comment]
conky 1.10.1 compiled Wed Jan  6 17:11:44 UTC 2016 for Linux 3.19.0-43-generic x86_64
think problem was in that what I'm not configure weather widget before first running. now output is clean:
conky
conky: desktop window (240000a) is subwindow of root window (225)
conky: window type - normal
conky: drawing to created window (0x3800001)
conky: drawing to double buffer
conky: forked to background, pid is 14486
 but may I ask one more question? not shows network traffic:
http://i.flamber.ru/files/st6/1255331886/1472847658_o.jpg

**Comment by zagortenay333** [comment]
You probably need to add your interface manually here: https://github.com/zagortenay333/Harmattan/blob/06da918b3c0b8cd78173b59ac14b8888b717a2ac/.harmattan-themes/Brown-Card/God-Mode/normal-mode/.conkyrc#L184

There is no way to figure out dynamically what your interface name is, so I had to hardcode a bunch of 'em. See https://github.com/zagortenay333/Harmattan/issues/23

Also see #1 for the alignment issue. Issues issues... :stuck_out_tongue_closed_eyes:

**Comment by ogerasymenko** [comment]
of course make dynamically adding interface will be difficult to implement.
I add interface name before make screen-shot:
cat .conkyrc | grep ens33
${if_existing /proc/net/route ens33}

**Comment by zagortenay333** [comment]
Does it work now?

**Comment by ogerasymenko** [comment]
unfortunately not

**Comment by zagortenay333** [comment]
You also have to add it in multiple spots, not just in that one line: https://github.com/zagortenay333/Harmattan/blob/06da918b3c0b8cd78173b59ac14b8888b717a2ac/.harmattan-themes/Brown-Card/God-Mode/normal-mode/.conkyrc#L184-L187

**Comment by ogerasymenko** [comment]
I should guess what need replace all mentions of interface name... Work, thanks a lot for your answers and work!
