### ISSUE TITLE
How to change form factor

### ISSUE THREAD

**Issue by HapCoderWei** [zagortenay333/Harmattan#27]
I love this theme,  but after i installed this, it just display the mini form. I want change it to full, but i can't find how to change it. How should i do? Thank you and your GOOD job!

**Comment by HapCoderWei** [comment]
By the way, I installed it on ubuntu 16.04 and it's version is the latest. Thanks a lot.

**Comment by zagortenay333** [comment]
That's what the paths in `harmattan-theme` dir do. You navigate your way to the theme you wish: https://github.com/zagortenay333/Harmattan/tree/master/.harmattan-themes/Button/God-Mode
