### ISSUE TITLE
Everything misaligned

### ISSUE THREAD

**Issue by tsoernes** [zagortenay333/Harmattan#28]
![screenshot from 2016-10-15 13-39-51](https://cloud.githubusercontent.com/assets/6782404/19409814/e03dc178-92dc-11e6-9771-ff8718416fec.png)

I haven't done anything to the conky config besides setting API key, city and ethernet.

Is there any way to shift all of the background down?

**Comment by zagortenay333** [comment]
Duplicate of #1
