### ISSUE TITLE
Can't get weather even with OpenWeatherMap API

### ISSUE THREAD

**Issue by elmagio** [zagortenay333/Harmattan#29]
I've downloaded the latest version and followed the instructions, as well as using voffset to correct the problems with alignment.

But I just can't seem to get the weather forecast to work. I'll put the whole .conkyrc I've configured in a pastebin linked [here](http://pastebin.com/zSuiK4hE) (API key used and location ID will be edited because it seems smart to do that), in case someone can find what I did wrong...

And here is a screenshot of how the Conky looks: 
![capture d ecran de 2016-11-09 23-41-00](https://cloud.githubusercontent.com/assets/14126056/20157578/15b65f74-a6d6-11e6-88af-fc5d72ad7341.png)

**Comment by zagortenay333** [comment]
What's the terminal output?

**Comment by elmagio** [comment]
[Here's](http://pastebin.com/p0YAC9sH) what the terminal output is when I launch conky manually.

**Comment by zagortenay333** [comment]
??
Did you follow the installation instructions? You don't have `jq` installed.

**Comment by elmagio** [comment]
Damn, I get where I messed up. Installed it long ago (along with `jq`), but didn't start using the new (OpenWeatherMap) version then because of the issue with voffset.

That was long ago, and I apparently uninstalled `jq` between then and now. Well, reinstalled it now, and it works. Sorry for the waste of time, thanks for your help !

**Comment by zagortenay333** [comment]
Np :smile:
