### ISSUE TITLE
Broken theme

### ISSUE THREAD

**Issue by extinctpotato** [zagortenay333/Harmattan#30]
I have a problem with every single theme. It just looks broken. I am running Ubuntu 16.04 if that helps.
![przechwycenie obrazu ekranu_2016-12-11_23-56-24](https://cloud.githubusercontent.com/assets/18371269/21084075/b7d6dee2-bffd-11e6-9d76-7fa05cdaaf32.png)

**Comment by zagortenay333** [comment]
:sob: It's a duplicate of the first issue #1
