### ISSUE TITLE
Temperature error

### ISSUE THREAD

**Issue by Taur10** [zagortenay333/Harmattan#31]
This just started yesterday I think, definitely not long ago, most certainly I noticed it yesterday.

![screenshot_2017-01-22_10-07-07](https://cloud.githubusercontent.com/assets/24876074/22193219/755ca8ee-e0ff-11e6-9361-bacec09c3d28.png)

I've checked the obvious variables, made sure they were accurate, and they are, so I'm a little flummoxed as to where to look for the problem.

**Comment by zagortenay333** [comment]
Any errors in the terminal on conky startup?

Also, show me the content of the files `~/.cache/weather.json` and `~/.cache/forecast.json`.

**Comment by Shadow12347** [comment]
I am getting the same error. When I cat those two files, it does show the abnormally high temperatures in both. But the location was set correctly, it shows the city name properly when I cat the caches.

**Comment by zagortenay333** [comment]
Show me the output of cat...

**Comment by Shadow12347** [comment]
I intentionally did not post the output because I would rather not broadcast my location to world lol... What are the fields you are looking for? I can just post those.

**Comment by zagortenay333** [comment]
Well just delete the name of the city from those files. :smile:

**Comment by Shadow12347** [comment]
weather.json:
{"coord":{"lon":xxx,"lat":xxx},"weather":[{"id":xxx,"main":"Clear","description":"clear sky","icon":"01d"}],"base":"stations","main":{"temp":289.595,"pressure":1005.96,"humidity":28,"temp_min":289.595,"temp_max":289.595,"sea_level":xxxx,"grnd_level":xxxxx},"wind":{"speed":1.85,"deg":37.5026},"clouds":{"all":0},"dt":1485797430,"sys":{"message":0.1679,"country":"US","sunrise":1485787699,"sunset":1485825695},"id":xxxxxx,"name":"xxxxx","cod":xxx}

forecast.json:
{"city":{"id":xxxxxx,"name":"xxxxx","coord":{"lon":xxxxx,"lat":xxxxx},"country":"US","population":0},"cod":"xxx","message":0.2871,"cnt":5,"list":[{"dt":1485806400,"temp":{"day":301.01,"min":276.69,"max":301.01,"night":276.69,"eve":285.5,"morn":286.95},"pressure":968.56,"humidity":31,"weather":[{"id":xxx,"main":"Clear","description":"clear sky","icon":"01d"}],"speed":1.31,"deg":39,"clouds":0},{"dt":1485892800,"temp":{"day":294.45,"min":276.15,"max":294.45,"night":276.15,"eve":282.73,"morn":276.41},"pressure":966.51,"humidity":32,"weather":[{"id":xxx,"main":"Clear","description":"clear sky","icon":"01d"}],"speed":1.06,"deg":188,"clouds":0},{"dt":1485979200,"temp":{"day":287.52,"min":275.69,"max":291.6,"night":279.51,"eve":291.6,"morn":275.69},"pressure":980.2,"humidity":0,"weather":[{"id":xxx,"main":"Clear","description":"clear sky","icon":"01d"}],"speed":1.42,"deg":55,"clouds":0},{"dt":1486065600,"temp":{"day":287.73,"min":278.15,"max":290.27,"night":280.33,"eve":290.27,"morn":278.15},"pressure":978.93,"humidity":0,"weather":[{"id":xxx,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"speed":1.13,"deg":101,"clouds":41},{"dt":1486152000,"temp":{"day":284.64,"min":279.46,"max":287.35,"night":279.95,"eve":287.35,"morn":279.46},"pressure":977.66,"humidity":0,"weather":[{"id":xxx,"main":"Rain","description":"moderate rain","icon":"10d"}],"speed":0.86,"deg":95,"clouds":54,"rain":3.31}]}

**Comment by zagortenay333** [comment]
Does the terminal output any errors?

**Comment by Shadow12347** [comment]
No none:

conky: desktop window (20001b) is subwindow of root window (273)
conky: window type - normal
conky: drawing to created window (0x1a00001)
conky: drawing to double buffer
conky: forked to background, pid is 23677

**Comment by zagortenay333** [comment]
Ah, did you change the units to `default` by any chance. If so, you are getting the temp in kelvin. :smile: Change it back to `metric` or `imperial`.

**Comment by Shadow12347** [comment]
Haha that's funny! I did actually change it to default, but the reason I changed it to default was because on imperial it was doing the same thing, and I was wondering if it would change anything, but it didn't. But switching back to imperial left me with the same results, it is still displaying in Kelvin.

**Comment by zagortenay333** [comment]
You might need to kill conky and start again a couple times to make it update the cache files. Or delete the cache files.

Imperial=fahrenheit
metric=celsius
default=kelvin

**Comment by Shadow12347** [comment]
Okay, that's weird, yeah it ended up working now! Before I changed it to default, I had it on imperial and it was displaying Kelvin, but after changing it back to imperial a second time, it updated and got the correct units. Thanks!

**Comment by zagortenay333** [comment]
Cheers.
