### ISSUE TITLE
Can't render pngs

### ISSUE THREAD

**Issue by tsoernes** [zagortenay333/Harmattan#32]
Inkscape is installed.

```
sh render-pngs

-e \e[1mEnter icon icon_size (skip for default): \e[0m

-e \e[1mEnter 1 or more colors (space or tab separated): \e[0m
render-pngs: 40: read: Illegal option -a
render-pngs: 47: render-pngs: icon_colors[0]=#000: not found
render-pngs: 57: render-pngs: Bad substitution
```

**Comment by tsoernes** [comment]
Bhwaa

Don't run with sh. Instead do 
`./render-pngs`

**Comment by zagortenay333** [comment]
Yeah it's a bash script :)

**Comment by tsoernes** [comment]
Is it supposed to render png's of the different themes? The output pngs can't be opened ..

**Comment by zagortenay333** [comment]
Can't help if you don't provide some info.

**Comment by tsoernes** [comment]
Forget the part about not being able to open them; there was something iffy with the default image viewer.

But the generated PNGs are just pictures of clouds and what not. Does it generate pictures of the themes (so I know which one to choose ..)?

**Comment by zagortenay333** [comment]
Did you read the README file? https://github.com/zagortenay333/Harmattan#rendering-weather-icons

Yes, it only renders weather icons.
