### ISSUE TITLE
Gnome classic, Arch LInux, Broken Borders

### ISSUE THREAD

**Issue by archevist** [zagortenay333/Harmattan#34]
Using Harmattan Conky script, no changes to default file except API key and city ID for weather. My window border are broken as shown in screenshot:

https://image.ibb.co/hmO4d5/Screenshot_from_2017_04_28_11_51_54.png

Works file under Budgie (which is Xorg) but Gnome (be it full or classic, Wayland) causing thie behavior.

Thank you for helpy.

**Comment by zagortenay333** [comment]
T_T ... #3
