### ISSUE TITLE
.conkyrc's won't load with Conky 1.10.x

### ISSUE THREAD

**Issue by Vistaus** [zagortenay333/Harmattan#36]
So I've compiled Conky 1.10.x from Git Master, then cloned your Git repo and followed all of the steps but the widgets just won't load. All it says in the terminal is:

```
date: invalid date ‘@null’
date: invalid date ‘@null’
[17:55:14] vistaus@vistaus-solus /home/vistaus/Downloads (0)
```

OS: Solus
DE: Budgie 10.3 (latest)

How to solve this?

**Comment by zagortenay333** [comment]
What does `jq -r .sys.sunrise ~/.cache/weather.json` say? Run it in a terminal.

**Comment by Vistaus** [comment]
It says 'null' :/

```
[21:03:26] vistaus@vistaus-solus /home/vistaus/Downloads (0) 
> jq -r .sys.sunrise ~/.cache/weather.json
null
[21:03:56] vistaus@vistaus-solus /home/vistaus/Downloads (0) 
> 

```

**Comment by zagortenay333** [comment]
What's inside the `~/.cache/weather.json` ?

**Comment by Vistaus** [comment]
This is what's inside:

`{"coord":{"lon":5.21,"lat":52.37},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"base":"stations","main":{"temp":20.68,"pressure":1024,"humidity":46,"temp_min":17,"temp_max":24},"visibility":10000,"wind":{"speed":4.1,"deg":250},"clouds":{"all":0},"dt":1494959100,"sys":{"type":1,"id":5204,"message":0.0163,"country":"NL","sunrise":1494906053,"sunset":1494963073},"id":2759879,"name":"Almere Stad","cod":200}`

**Comment by Vistaus** [comment]
Hmm, somehow the date error disappeared but it still can't find any images, or so it says:
```

[21:12:47] vistaus@vistaus-solus /home/vistaus/Downloads (0) 
> conky
conky: desktop window (2600011) is subwindow of root window (d5)
conky: window type - normal
conky: drawing to created window (0x4000001)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: forked to background, pid is 8710
[21:13:29] vistaus@vistaus-solus /home/vistaus/Downloads (0) 
> 

```

**Comment by zagortenay333** [comment]
The first problem maybe had to do with the fact that the weather file wasn't yet loaded.

To solve the other problem, try installing `conky-all`.

**Comment by Vistaus** [comment]
There's no package conky-all in Solus.

**Comment by zagortenay333** [comment]
Hmm, no clue then. What kinds of packages are there? Usually this one solved that way. #21

**Comment by Vistaus** [comment]
The only package in Solus is 'conky': https://git.solus-project.com/packages/conky/

Besides, I've compiled 1.10 from Git Master, doesn't that include 'all' already? (I've been using Linux for years now but I'm fairly new to Conky so correct me if I'm wrong)

**Comment by zagortenay333** [comment]
I've no clue. Maybe it needs to be compiled with some flags that enable all the features. The conky that you have right now doesn't recognize the variable `$image` which it should.

**Comment by Vistaus** [comment]
You're right! Turns out I needed to build Conky with IMLIB2 support ON. Now it looks a lot better, although I still have a strange, thick black border around Conky:

![screenshot from 2017-05-16 21 32 10](https://cloud.githubusercontent.com/assets/1716229/26124565/3fd48474-3a7f-11e7-87cf-95a4f7b25c12.png)

Do you know how to solve that?

**Comment by zagortenay333** [comment]
You have also the issue that conky is completely out of alignment :rofl: Conky is a mess, it was never designed for what I'm doing with it..

See #1 and #3. Gonna close this now.

**Comment by Vistaus** [comment]
I thought I read that was fixed in Conky 1.10.x That's why I went for 1.10.x rather than 1.9 from the Solus repos. Thanks anyway for all of your help, I'll try the suggestions from #1 and #3.

**Comment by Vistaus** [comment]
Using feh didn't solve it. Changing the voffset doesn't seem to have any effect either. Man, this sucks 😞 

Edit: wait a sec, I found the solution!!! Disabling double buffer removed the black border. Although it does display a slight transparent border but on a light background it's not all that noticeable so I can live with that.

**Comment by BeforeFlight** [comment]
> date: invalid date ‘@null’
date: invalid date ‘@null’

Had same error till now. And it seems like just waiting for couple of minutes fix problem..
