### ISSUE TITLE
Wrong current temperature

### ISSUE THREAD

**Issue by Vistaus** [zagortenay333/Harmattan#37]
It keeps displaying 25C, 24 hours a day. I did put in the right API key in the conkyrc and also the right city ID. It does update the forecast, however. How to solve this?

OS: Solus
Conky: 1.10.x
Conky Harmattan: latest Git Master

Edit: when I right-click on the widget, it does update. Is that intended behavior?

**Comment by zagortenay333** [comment]
Are the cache files updated while the conky isn't?
The cache files are `~/.cache/weather.json` and `~/.cache/forecast.json`

I believe that you wrote how you changed the buffer config in the conky or something like that. Maybe that's the issue.

Now that I think of it, I should have namespaced these...

**Comment by Vistaus** [comment]
Yes, I disabled double buffer to partly fix the black border issue. Maybe that's the issue indeed. I'll keep an eye on it, thanks.

**Comment by zagortenay333** [comment]
Did it fix it?

**Comment by Vistaus** [comment]
It seems to have fixed itself lol. Will close this for now. I'll reopen it if this issue shows up again.
