### ISSUE TITLE
Images does not load in conky

### ISSUE THREAD

**Issue by NatanCC** [zagortenay333/Harmattan#4]
Instead images I have ${image}.
I'm using in Xubuntu 15.05

**Comment by zagortenay333** [comment]
What is the output of the terminal?

**Comment by NatanCC** [comment]
Sorry, but I solved the problem installing conky-all. The terminal output had many "unknow variable image".
I found the solution here: https://bugs.launchpad.net/ubuntu/+source/conky/+bug/1439879

Thank!!! Your conkys are so Fantastics!!

**Comment by zagortenay333** [comment]
Good to hear that.
