### ISSUE TITLE
jq is a requisite and should be indicated in the docs

### ISSUE THREAD

**Issue by ayito** [zagortenay333/Harmattan#42]
Hello!
First things first, thanks for your great work!

Now to the point: I just find out that weather wasn't working, and when executing conky from the command line, I got: 

> cp: no se puede efectuar `stat' sobre '/home/ayito/.harmattan-assets/icons/#fff__32/**.png**': No existe el archivo o el directorio

Notice: **.png**

The code that writes the name of the ".png" file was abound the 250 line in .conkyrc (after configuration):
`$(jq .list[0].weather[0].id ~/.cache/forecast.json).png`

when I tried at the command line:
`$echo $(jq .list[0].weather[0].id ~/.cache/forecast.json).png
`
I got 

> El programa «jq» no está instalado. Puede instalarlo escribiendo:
sudo apt install jq

After I installed the program "jq" the problema was solved.

This wasn't mentioned in the INSTALL docs and may be kind of hard to find out for some people (It cost me some time myself to figure it out).

So, I suggest to comment it in the INSTALL docs and also mention other software pre-requisites just to have a smooth installation and experience with the software.

Thanx again for the hard work!

**Comment by zagortenay333** [comment]
Yes it is mentioned in the README; in bold letters.

**Comment by ayito** [comment]
Oh, I see it, first line! thank you.
