### ISSUE TITLE
console window's current visible content used as background

### ISSUE THREAD

**Issue by gsantner** [zagortenay333/Harmattan#45]
Hi there,
I wanted to try harmattan, but I keep getting the console windows's current UI as background somehow.
I looked also into issue no 3, which doesn't seem to be the same issue. See screenshot below

![screenshot_2017-08-30__19-07_2](https://user-images.githubusercontent.com/6735650/29885372-d0744656-8db6-11e7-82c4-d500e6ddb14f.png)

My conky version:
<details>
conky 1.10.6_pre compiled Mit Aug 30 17:46:09 CEST 2017 for Linux 4.12.8-2-ARCH x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
</details>

**Comment by zagortenay333** [comment]
It's the same issue as #3.
