### ISSUE TITLE
Thanks and notes

### ISSUE THREAD

**Issue by bablat** [zagortenay333/Harmattan#48]
Thank you for a stylish set of themes. A few minor things you may want to know:

- I didn't have `jq` installed (quick fix with `sudo apt install jq -y`), weather was broken. Not sure if it's a conky dependency or specific to your theme, but it should be noted as a dependency.
- The network configuration was off as my main network adapter is `eno1`. Manually replacing it in the configuration files is a bit awkward (I used `d .harmattan-themes/ -name '.conkyrc' -execdir sed -i 's/ppp0/eno1/g' {} \;`). Perhaps consider prompting for the network interface name when installing the theme, or detect the first one that has a link?
- Last but not least, I couldn't figure out how to import these into `conky-manager`, so I'm stuck using the preview script.

**Comment by zagortenay333** [comment]
Thx :smile: 

In order:
* jq is already listed as a dependency.
* Can't be detected automatically.
* Harmattan doesn't support conky-manager (and never will; too lazy to deal with that.)
