### ISSUE TITLE
How to know what theme correspond to the preview?

### ISSUE THREAD

**Issue by Kuchiriel** [zagortenay333/Harmattan#51]

**Comment by jdelamater99** [comment]
Assuming you downloaded and extracted the zip to the Downloads folder
`~/Downloads/Harmattan-master/preview`

`Press h/l to scroll through themes.`
`Press j/k to scroll through formats.`
`Press n/m to scroll through modes.`
`Press i to install and add API key/location info.`
`Press r to revert to your backed-up .conkyrc`
`Press q or ctrl-c to quit.`
