### ISSUE TITLE
next day weather no update 

### ISSUE THREAD

**Issue by ryufrvr** [zagortenay333/Harmattan#54]
![2018-08-21-200642_1366x768_scrot](https://user-images.githubusercontent.com/31278954/44414119-87e05380-a55c-11e8-98e6-a93a0fa68e0a.png)

Next day weather no update. Api and city id on .conkyrc is correct.

**Comment by jdelamater99** [comment]
See my comment in this thread:
https://github.com/zagortenay333/Harmattan/issues/56#issuecomment-526633939
