### ISSUE TITLE
Shouldn't the next days show the weather preview too?

### ISSUE THREAD

**Issue by hrqmonteiro** [zagortenay333/Harmattan#56]
![2019-01-08-175236_287x289_scrot](https://user-images.githubusercontent.com/17055027/50855165-436c1d80-136e-11e9-9cc7-9aaeea097fcf.png)
Only the current day shows correctly, everyday the others still show 0º/º

**Comment by jdelamater99** [comment]
Tracked the answer to down as a missing dependency.  The parse_weather script uses bc (lines 60 & 74), which is a command line calculator.  You can test if this is the problem you are having my issuing this command in a terminal window.

This is called in .conkyrc, line 126, at least in the OMG-Ubuntu! theme
`~/.harmattan-assets/parse_weather 'avg' '.main.temp_min' '0'`

If bc isn't installed, you'll get the following error message  
`/home/pi/.harmattan-assets/parse_weather: line 60: bc: command not found`
`/home/pi/.harmattan-assets/parse_weather: line 60: bc: command not found`
`/home/pi/.harmattan-assets/parse_weather: line 60: bc: command not found`
`/home/pi/.harmattan-assets/parse_weather: line 74: bc: command not found`

If that's the case, install bc using the following command
`sudo apt-get install bc`

![image](https://user-images.githubusercontent.com/4734210/64030456-9f113400-cb14-11e9-94e8-9387135f39e7.png)

**Comment by zagortenay333** [comment]
I guess this is fixed then so closing.
