### ISSUE TITLE
unknown variable image

### ISSUE THREAD

**Issue by whoiswentz** [zagortenay333/Harmattan#7]
I am having this problem, unknown variable image, the .harhattan-theme is in home folder, but i get this messages on terminal.

![untitled](https://cloud.githubusercontent.com/assets/9222432/9815961/539015a2-5870-11e5-87f1-301375969700.png)

My conky looks like...

![untitled2](https://cloud.githubusercontent.com/assets/9222432/9815981/77173ffa-5870-11e5-856d-989628670dbf.png)

My conky configuration file this untouchable.
Please help me.

**Comment by zagortenay333** [comment]
What version of conky are you using?

**Comment by whoiswentz** [comment]
Conky 1.9.0 compiled Mon Mar 23 17:14:17 UTC 2015 for Linux 3.2.0-77-generic (x86_64)

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 X11:
- Xdamage extension
- XDBE (double buffer extension)
- Xft
- ARGB visual
  
  Music detection:
- MPD
- MOC
  
  General:
- math
- hddtemp
- portmon
- wireless
- config-output
- apcupsd
- iostats
- ncurses
- Lua
  
  Lua bindings:

**Comment by zagortenay333** [comment]
Try installing the imlib2 package.

**Comment by whoiswentz** [comment]
did not work :(

**Comment by zagortenay333** [comment]
Still getting the same error? Is imlib2 showing up after `conky -v` Here is my output:
```sh
```

**Comment by zagortenay333** [comment]
Still getting the same error? Here is my output for `conky -v`:

```
Conky 1.9.0 compiled Wed Feb 19 18:40:53 UTC 2014 for Linux 3.2.0-37-generic (i686)

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 X11:
  * Xdamage extension
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 General:
  * math
  * hddtemp
  * portmon
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * config-output
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Lua

  Lua bindings:
   * Cairo
   * Imlib2
```

**Comment by zagortenay333** [comment]
It's complaining that the variable `$image` is unknown, yet that is a standard variable in conky: http://conky.sourceforge.net/variables.html

**Comment by zagortenay333** [comment]
Does this happen with all conky themes for you?

**Comment by zagortenay333** [comment]
Does it work now?

**Comment by RavensKrag** [comment]
I had the same problem, and I solved it, so I figured I'd post a solution, in case anyone else ends up having the same problem. (This page ranks pretty high on Google.)

In Ubuntu, apparently you need to install the `conky-all` package to get lua scripting support in Conky. Without lua support, conky doesn't know what to do with the `$image` variable

According to this link:
http://mylittledesktop.blogspot.com/2009/10/quick-explanation-to-conky-packages-in.html

> conky-all includes almost all of the available support:
> 
> X11, XDamage, XDBE, Xft, MPD, MOC, math, hddtemp, portmon, RSS, curl, Weather (METAR and XOAP), wireless, IBM, nvidia, eve-online, Imlib2, ALSA mixer, apcupsd, I/O stats, Lua and Lua bindings for the cairo and imlib2 libraries

The other packages lack the Lua bindings for imlib2.

(If this doesn't solve the problem, you may be experiencing this bug: https://bugs.launchpad.net/ubuntu/+source/conky/+bug/1439879)
