### ISSUE TITLE
Screenshots of all themes

### ISSUE THREAD

**Issue by manishrjain** [zagortenay333/Harmattan#8]
One screenshot of each theme would be really useful. It's hard to judge how they look by just the name. The other way requires trying out each theme one by one to figure out how they look, and pick a favourite.

**Comment by zagortenay333** [comment]
Sorry, not gonna do it.

For one thing, I would need to maintain about 100 screenshots to do that. (_22 themes, 4 form factors for each, 2 weather mods for most._) Even if I only maintained 22 scrots, It would still be too much.

Also, they would need to be hosted somewhere else.

I also think that there is a bit of a charm in trying the themes out and not knowinig how they look beforehand. :smile:

**Comment by nicolasdanelon** [comment]
images can be hosted here, in github. 
but yes, that's a lot of work useless

**Comment by manishrjain** [comment]
First of all, I love these themes. They look awesome! Thanks!

It is quite some work to create 22 screenshots, no doubt. But, imagine having every new user have to repeat this work. Doing this as a one-off is still better. Particularly, when you are already spending time building these beautiful themes.

Even if this sounds infeasible, I'm sure you can find a middle ground. For e.g., instead of a screenshot, a text phrase explaining that the theme is, for e.g., [white background with orange text], [blue on black] etc., and some pointers on which to choose if you're new to this.. your favourites etc. Anything which cuts down on having to iterate through all 22 themes...

Again, remember, if this sounds like too much work to you, it definitely is impossible work for new users, particularly when they're unsure if this is the right solution for them, out of all the possibilities there are on the net. Maybe some people will try out all of them, most would just try 1 or 2 before either choosing or giving up.

Whatever you decide, keep up the good work!

**Comment by zagortenay333** [comment]
I'm definitely not going to maintain scrots. I used to have small descriptions, but they are pretty much useless.
